# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src
# Target is a subdirs project 

SOURCES += adresis.cpp 
SUBDIRS += dlib \
           servidor \
           cliente 
KDEV_QTVER = 3 
TARGET = ../bin/adresis 
CONFIG += release \
          warn_on 
TEMPLATE = subdirs 
