# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/cliente
# Target is a subdirs project 

SUBDIRS += theme \
           lib \
           network \
           modules \
           shell 
KDEV_QTVER = 4
CONFIG += release \
warn_on
TEMPLATE = subdirs
