# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/cliente/modules
# Target is a subdirs project 

SUBDIRS += users \
           space \
           reserves 
KDEV_QTVER = 4
CONFIG += release \
warn_on
TEMPLATE = subdirs
