# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/lib
# Target is a library:  adlib

INSTALLS += target 
target.path = /lib 
TARGET = adlib 
CONFIG += release \
          warn_on \
          dll 
TEMPLATE = lib 
