# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/lib
# Target is a library:  adlib

INSTALLS += target 
target.path = /lib 
HEADERS += adevent.h \
           adeventhandler.h \
           global.h \
           adeventfactory.h 
SOURCES += adevent.cpp \
           adeventhandler.cpp \
           adeventfactory.cpp 
TARGET = adlib
CONFIG += release \
warn_on \
dll
TEMPLATE = lib

include(lib_config.pri)

