# File generated by kdevelop's qmake manager. 
# ------------------------------------------- 
# Subdir relative project main directory: ./src/cliente
# Target is a subdirs project 

SUBDIRS += lib \
           modules \
           shell \
           theme 
KDEV_QTVER = 3
CONFIG += release \
warn_on
TEMPLATE = subdirs
